### ISSUE TITLE
Latest Discord update changed CSS classes

### ISSUE THREAD

**Issue by minhla** [Dyzean/Tokyo-Night#10] opened 2022-01-11 13:32 UTC
![image](https://user-images.githubusercontent.com/23179654/148952066-711a48ae-7ef9-4b9a-b50a-2b327e9762cb.png)

I want to help with fixing/updating this theme, since I'm using Tokyo Night in my VS Code as well! Let me know.

**Update:** By using this [tool](https://laynetheepic.github.io/projects/pc-theme-converter/), the theme seems to have been fixed. [I am linking the new main.css file that is working properly now here for your convenience.](https://pastebin.com/jjj4ma92) . Maybe I'll submit a new merge request as well.

**Comment by Dyzean** [comment] 2022-01-12 08:55
Thanks for your issue report and PR, i'll merge the PR after i checked if its working as intended 👍🏼

**Comment by Dyzean** [comment] 2022-01-12 08:58
I might release v2 tho with this issue fixed as well

**Comment by minhla** [comment] 2022-01-13 11:24
I've tested the theme with the new CSS classes and it's working fine 👍🏼 You can test it again and let me know if something is out of place.

**Comment by Dyzean** [comment] 2022-01-14 21:49
Fixed in this commit [f72e52](https://github.com/Dyzean/Tokyo-Night/commit/4f72e5282c7029a408b3a71052d659633ff3098b)

**Closed** 2022-01-14 21:50 UTC
